### ISSUE TITLE
mods plz

### ISSUE THREAD

**Issue by otakup0pe** [otakup0pe/avakas#28]
This python is something else. One file, one purpose.

Change it up to use separate modules. As a precursor to testing it.

Should probably also abstract out the different project version extraction into objects or something.

![honk](https://64.media.tumblr.com/14e97cb9a5c4f96615f78869dca94ae9/tumblr_pyt5ndGRPu1w5ruo0o1_400.gifv)

**Comment by mjuarez** [comment]
This can be closed now?

**Comment by otakup0pe** [comment]
by golly i think it can
