### ISSUE TITLE
Question re: preference on naming of Python pyproject.toml flavor

### ISSUE THREAD

**Issue by tyler-jachetta** [otakup0pe/avakas#39]
Apparently an `@` mention doesn't work in tyler-jachetta land, @otakup0pe , but, as I asked here: https://github.com/tyler-jachetta/avakas/commit/daedcfa43b6524310315cccffdd5dc4929f0371f, 

I was of several minds on what to name this. `python.(?:pep621|pyproject.toml)?`? I feel like naming should be consistent between module, class, registered name, and `PROJECT_TYPE`, I kinda like python[-_]pep621,but feels like it's maybe too esoteric a name, what would you prefer?

**Comment by otakup0pe** [comment]
I prefer explicit over implicit. Given there is a pep involved, maybe use that in the naming?
