### ISSUE TITLE
Supported Python[s]

### ISSUE THREAD

**Issue by hunnybear** [otakup0pe/avakas#58]
The container uses Python 3.8, so I started targeting my [pep621 flavor](https://github.com/tyler-jachetta/avakas/tree/tjachetta/pep-621-pyproject-toml-support) at 3.8. The testing jobs in the github CI [here](https://github.com/otakup0pe/avakas/blob/e4771cd7fdda5abb77a1a14379c7f61caba9d202/.github/workflows/build.yml#L17) seems to indicate that maybe Python 3.7+ is being targeted.

There should be a python version constraint in the setup.py, or, if we wanted to go to using poetry for managing the package/dependencies themselves, I'm totally open to doing that. I'll open a new issue to propose/talk about that

**Comment by hunnybear** [comment]
hm just saw @mjuarez 's add and remove of poetry earlier this month. Is that a rejection of using poetry, or is that a direction that you just decided to not continue with? (I'll gladly look into working on that unless it was decided that we just shouldn't set up dependencies and package with poetry

**Comment by hunnybear** [comment]
so, just saw that @mjuarez added and removed poetry earlier, but https://github.com/otakup0pe/avakas/pull/47#pullrequestreview-546683999 suggests that we might still be interested in using it if a) avakas didn't require any dynamic versioning for itself (don't think this is a bad thing imo) b) the console scripts entry point has a replacement (it does in poetry)

I had started poking at adding poetry in so that my testing on the pep621 stuff worked nicer, but since I saw that it had been added and removed in the past, figured I'd check in before burning any cycles

**Comment by otakup0pe** [comment]
Mike pulled poetry because we didn't want to straight up replace `setup.py` with poetry quite yet. There are still some glitches that poetry is working through before it is ready for that. One of the issues is dynamic versioning.

**Comment by otakup0pe** [comment]
Regarding python versions, we should probably also test against 3.8.

**Comment by hunnybear** [comment]
are we limiting to 3.8 + ? do we support 2.x at all?

**Comment by otakup0pe** [comment]
2.x is dead to us...
