### ISSUE TITLE
Successive prerelease bumps do not actually bump the prerelease version

### ISSUE THREAD

**Issue by tyler-jachetta** [otakup0pe/avakas#63]
When one attempts to do two prerelease bumps for the same bump, the pre-release component does not get incremented properly. I have created a branch [here](https://github.com/tyler-jachetta/avakas/tree/tjachetta/add_test_for_successive_prereleases) with tests that fail which I believe should pass.

If the tests capture desired behavior, I can work on resolving this issue

**Comment by tyler-jachetta** [comment]
specifically, here are the above mentioned tests: https://github.com/tyler-jachetta/avakas/blob/ece42c1d3d3a3d91e7444fc2bdaed21fa597a764/tests/integration/prerelease.bats#L182-L194

**Comment by otakup0pe** [comment]
Hmm can we get a (draft) PR open with these failing tests so we can see the output? Or maybe throw it in a gist?
